<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13581" started-at="2020-02-27T18:45:26Z" finished-at="2020-02-27T18:45:40Z">
    <groups>
    </groups>
    <test name="ParticularTest" duration-ms="13581" started-at="2020-02-27T18:45:26Z" finished-at="2020-02-27T18:45:40Z">
      <class name="Test.TestCase">
        <test-method status="FAIL" signature="launchMyAccountHome()[pri:0, instance:Test.TestCase@1add175]" name="launchMyAccountHome" is-config="true" duration-ms="0" started-at="2020-02-28T00:15:26Z" finished-at="2020-02-28T00:15:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Test.TestCase.launchMyAccountHome(TestCase.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchMyAccountHome -->
        <test-method status="SKIP" signature="addItem()[pri:0, instance:Test.TestCase@1add175]" name="addItem" duration-ms="10" started-at="2020-02-28T00:15:40Z" description="Add an item to the cart." finished-at="2020-02-28T00:15:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addItem -->
        <test-method status="SKIP" signature="add_MultipleItems()[pri:0, instance:Test.TestCase@1add175]" name="add_MultipleItems" duration-ms="10" started-at="2020-02-28T00:15:40Z" description="Add multiple item to the cart." finished-at="2020-02-28T00:15:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_MultipleItems -->
        <test-method status="SKIP" signature="disposeWebdrive()[pri:0, instance:Test.TestCase@1add175]" name="disposeWebdrive" is-config="true" duration-ms="0" started-at="2020-02-28T00:15:40Z" finished-at="2020-02-28T00:15:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disposeWebdrive -->
      </class> <!-- Test.TestCase -->
    </test> <!-- ParticularTest -->
  </suite> <!-- Suite -->
</testng-results>
